<script type="text/javascript" src="/home/assets/js/jquery.min.js"></script>
<script type="text/javascript" src="/home/assets/js/jquery-ui.min.js"></script>
<script type="text/javascript" src="/home/assets/js/bootstrap.min.js"></script>
<script type="text/javascript" src="/home/assets/js/bootstrap.notify.min.js"></script>
<script type="text/javascript" src="/home/assets/js/promise.js"></script>
<script type="text/javascript" src="/home/assets/js/handlebars-v4.0.5.js"></script>
<script type="text/javascript" src="/home/assets/js/app/common.js"></script>
<script type="text/javascript" src="/home/assets/js/app/handlebarTemplates.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/v/bs-3.3.7/jszip-2.5.0/pdfmake-0.1.18/dt-1.10.13/af-2.1.3/b-1.2.4/b-colvis-1.2.4/b-flash-1.2.4/b-html5-1.2.4/b-print-1.2.4/cr-1.3.2/fc-3.2.2/fh-3.1.2/kt-2.2.0/r-2.1.1/rr-1.2.0/sc-1.4.2/se-1.2.0/datatables.min.js"></script>
<script type="text/javascript" src="/home/assets/js/app/app.js"></script>  
<div id='search-dialog' class='search-dialog'></div>